clothes:
  outputs:
    dev:
      dbname: airflow
      host: localhost
      pass: '1234'
      port: 25432
      schema: test
      threads: 1
      type: postgres
      user: postgres
  target: dev
dbt_test:
  outputs:
    dev:
      dbname: test
      host: localhost
      pass: '1234'
      port: 25432
      schema: test_schema
      threads: 1
      type: postgres
      user: postgres
  target: dev
