# ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: airflow
  POSTGRES_PASSWORD: "1234"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
    "postgresql+psycopg2://postgres:1234@postgres:5432/airflow"
  _AIRFLOW_WWW_USER_CREATE: "true"
  _AIRFLOW_WWW_USER_USERNAME: "admin"
  _AIRFLOW_WWW_USER_PASSWORD: "test1234"

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow-webserver
spec:
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow
          image: apache/airflow
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["bash", "-c"]
          args:
            - |
              airflow db migrate
              airflow webserver
          ports:
            - containerPort: 8080

# Services
--- 
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  labels:
    app: airflow-webserver
spec:
  ports:
    - port: 5432
  selector:
    app: airflow-webserver
